apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/workshop/lab-container-security-01.yaml
- resources/workshop/lab-container-security-02.yaml
- resources/workshop/lab-configuration-management.yaml
- resources/workshop/lab-tas4ops.yaml
- resources/workshop/lab-k8-networking.yaml
# - resources/workshop/lab-getting-started-with-octant.yaml
# - resources/workshop/lab-spring-boot-k8s-getting-started.yaml
# - resources/workshop/lab-container-basics.yaml
# - resources/workshop/lab-getting-started-with-carvel.yaml
- resources/workshop/lab-spring-boot-k8s-probes.yaml
# - resources/workshop/lab-spring-boot-k8s-skaffold.yaml
# - resources/workshop/lab-python-containers.yaml
- resources/workshop-portal.yaml

